openapi: 3.1.0
info:
  title: Inventory Service
  description: My service
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api/v1'
paths:
  /users:
    post:
      summary: Create user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: User created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Update user by ID
      operationId: updateUserById
      parameters:
        - $ref: '#/components/parameters/userId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserRequest'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'

components:
  schemas:
    UserBase:
      type: object
      properties:
        firstName:
          type: string
          example: 'John'
        lastName:
          type: string
          example: 'Doe'
        email:
          type: string
          example: 'test@example.com'
      required:
        - firstName
        - lastName
        - email
    CreateUserRequest:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            password:
              type: string
              example: 'securePassword123'
          required:
            - password
    UpdateUserRequest:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
    UserResponse:
      allOf:
        - $ref: '#/components/schemas/UserBase'
        - type: object
          properties:
            id:
              type: integer
              format: int64
              example: 1
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example:
            - 'Email already exists'
            - 'User not found'
  parameters:
    userId:
      in: query
      name: userId
      description: User ID
      required: true
      schema:
        type: integer
        format: int64
        minimum: 1
        example: 1